Add link to confluence
pulibrary/dls-handbook pull request #72
Opened 2023-02-23 15:26 UTC by hackartisan

closes #45

2023-03-01 20:49 UTC, sdellis requested changes
@hackartisan Is it possible to give some indication of the types of information that can be found in the confluence wiki, similar to the other resources in the list?

Maybe something like this, which is found on the front page of the wiki? 

> Confluence is a wiki (collaborative workspace) used by PUL staff to manage documentation, policies, committee materials, project documents, and other internal documents.

2023-03-01 23:55 UTC, tpendragon approved these changes

2023-03-02 14:21 UTC, hackartisan commented
@sdellis I added that. take another look?

2023-03-02 21:24 UTC, sdellis approved these changes
LGTM 👍

2023-03-02 21:24 UTC, merged